version: '3.8'

services:
  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5430:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db